/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.queueing;

import javax.swing.JOptionPane;

/**
 *
 * @author lucky
 */
public class ADMIN extends javax.swing.JFrame {

    /**
     * Creates new form ADMIN
     */
    public ADMIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        USA = new javax.swing.JTextField();
        JPY = new javax.swing.JTextField();
        EURO = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        confirm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 150, 900, 550));
        setMinimumSize(new java.awt.Dimension(900, 550));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(9, 507, 90, 30);

        USA.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        USA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        USA.setText("56.5");
        USA.setBorder(null);
        USA.setEnabled(false);
        USA.setOpaque(true);
        jPanel1.add(USA);
        USA.setBounds(620, 280, 160, 50);

        JPY.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        JPY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JPY.setText("0.38");
        JPY.setBorder(null);
        JPY.setEnabled(false);
        JPY.setOpaque(true);
        jPanel1.add(JPY);
        JPY.setBounds(620, 410, 160, 50);

        EURO.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        EURO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EURO.setText("60.2");
        EURO.setBorder(null);
        EURO.setEnabled(false);
        EURO.setOpaque(true);
        jPanel1.add(EURO);
        EURO.setBounds(620, 350, 160, 40);

        edit.setBorderPainted(false);
        edit.setContentAreaFilled(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit);
        edit.setBounds(349, 490, 90, 30);

        confirm.setBorderPainted(false);
        confirm.setContentAreaFilled(false);
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        jPanel1.add(confirm);
        confirm.setBounds(460, 490, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final Design/admin page.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 550);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int option = JOptionPane.showConfirmDialog(null,"Are you sure you want to logout?","Logout?",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        
        if (option == JOptionPane.OK_OPTION) {
        this.setVisible(false);
        new EMPLOYEE().setVisible(true);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        String usd = USA.getText();
        String euro = EURO.getText();
        String jpy = JPY.getText();   
        
        QUEUEING.USD.add(usd);
        QUEUEING.EURO.add(euro);
        QUEUEING.JPY.add(jpy);
        
        USA.setEnabled(false);
        EURO.setEnabled(false);
        JPY.setEnabled(false);
        
    }//GEN-LAST:event_confirmActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        USA.setEnabled(true);
        EURO.setEnabled(true);
        JPY.setEnabled(true);
    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EURO;
    private javax.swing.JTextField JPY;
    private javax.swing.JTextField USA;
    private javax.swing.JButton confirm;
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
