/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.queueing;
import static com.mycompany.queueing.QUEUEING.nameA;
import static com.mycompany.queueing.QUEUEING.queueA;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**

 * @author lucky
 */
public class CUSTOMER extends javax.swing.JFrame {
    

    /**
     * Creates new form CUSTOMER
     */
    public CUSTOMER(  ) {
        initComponents();
        name.setBackground(new Color(0, 0, 0, 0));
        amount.setBackground(new Color(0, 0, 0, 0));
        address.setBackground(new Color(0, 0, 0, 0));
        fname.setBackground(new Color(0, 0, 0, 0));
        bday.setBackground(new Color(0, 0, 0, 0));
        email.setBackground(new Color(0, 0, 0, 0));
        occupation.setBackground(new Color(0, 0, 0, 0));
        number.setBackground(new Color(0, 0, 0, 0));
        change.setBackground(new Color(0, 0, 0, 0));
        convert.setBackground(new Color(0, 0, 0, 0));
        name3.setBackground(new Color(0, 0, 0, 0));
        amount3.setBackground(new Color(0, 0, 0, 0));
        paytoOptions.setBackground(new Color(0, 0, 0, 0));
        paytoOptions.setSelectedItem(null);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        exchange = new javax.swing.JButton();
        application = new javax.swing.JButton();
        bills = new javax.swing.JButton();
        dashboard = new javax.swing.JLabel();
        BP = new javax.swing.JPanel();
        paytoOptions = new javax.swing.JComboBox<>();
        name = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        confirm = new javax.swing.JButton();
        BPbg = new javax.swing.JLabel();
        APLI = new javax.swing.JPanel();
        address = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        bday = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        occupation = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        cancel1 = new javax.swing.JButton();
        confirm1 = new javax.swing.JButton();
        APLIbg = new javax.swing.JLabel();
        FE = new javax.swing.JPanel();
        amount3 = new javax.swing.JTextField();
        name3 = new javax.swing.JTextField();
        convert = new javax.swing.JComboBox<>();
        confirm3 = new javax.swing.JButton();
        cancel3 = new javax.swing.JButton();
        change = new javax.swing.JComboBox<>();
        FEbg = new javax.swing.JLabel();
        queue = new javax.swing.JPanel();
        queuenum = new javax.swing.JLabel();
        queuebg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(757, 0));
        setMinimumSize(new java.awt.Dimension(800, 400));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(null);

        container.setLayout(new java.awt.CardLayout());

        main.setLayout(null);

        exchange.setBorderPainted(false);
        exchange.setContentAreaFilled(false);
        exchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exchangeActionPerformed(evt);
            }
        });
        main.add(exchange);
        exchange.setBounds(250, 300, 310, 40);

        application.setBorderPainted(false);
        application.setContentAreaFilled(false);
        application.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicationActionPerformed(evt);
            }
        });
        main.add(application);
        application.setBounds(250, 240, 310, 40);

        bills.setBorderPainted(false);
        bills.setContentAreaFilled(false);
        bills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billsActionPerformed(evt);
            }
        });
        main.add(bills);
        bills.setBounds(250, 180, 310, 40);

        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final Design/customer dashboard.png"))); // NOI18N
        main.add(dashboard);
        dashboard.setBounds(0, 0, 800, 400);

        container.add(main, "main");

        BP.setLayout(null);

        paytoOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maynilad", "Meralco", "Globe", "PLDT", "Smart", "" }));
        paytoOptions.setSelectedIndex(-1);
        paytoOptions.setBorder(null);
        BP.add(paytoOptions);
        paytoOptions.setBounds(90, 210, 300, 30);

        name.setBorder(null);
        BP.add(name);
        name.setBounds(80, 160, 320, 30);

        amount.setBorder(null);
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        BP.add(amount);
        amount.setBounds(470, 160, 300, 30);

        cancel.setBorderPainted(false);
        cancel.setContentAreaFilled(false);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        BP.add(cancel);
        cancel.setBounds(300, 360, 90, 30);

        confirm.setBorderPainted(false);
        confirm.setContentAreaFilled(false);
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        BP.add(confirm);
        confirm.setBounds(410, 360, 90, 30);

        BPbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final Design/customer bills payment.png"))); // NOI18N
        BP.add(BPbg);
        BPbg.setBounds(0, 0, 800, 400);

        container.add(BP, "BP");

        APLI.setLayout(null);

        address.setBorder(null);
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        APLI.add(address);
        address.setBounds(110, 260, 270, 20);

        fname.setBorder(null);
        APLI.add(fname);
        fname.setBounds(110, 146, 270, 30);

        bday.setToolTipText("");
        bday.setBorder(null);
        bday.setName(""); // NOI18N
        bday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdayActionPerformed(evt);
            }
        });
        APLI.add(bday);
        bday.setBounds(110, 310, 270, 30);

        email.setBorder(null);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        APLI.add(email);
        email.setBounds(500, 200, 260, 30);

        occupation.setBorder(null);
        occupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationActionPerformed(evt);
            }
        });
        APLI.add(occupation);
        occupation.setBounds(490, 150, 270, 20);

        number.setText("+63");
        number.setBorder(null);
        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });
        APLI.add(number);
        number.setBounds(110, 200, 270, 30);

        cancel1.setBorderPainted(false);
        cancel1.setContentAreaFilled(false);
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });
        APLI.add(cancel1);
        cancel1.setBounds(300, 360, 90, 30);

        confirm1.setBorderPainted(false);
        confirm1.setContentAreaFilled(false);
        confirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm1ActionPerformed(evt);
            }
        });
        APLI.add(confirm1);
        confirm1.setBounds(410, 360, 90, 30);

        APLIbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final Design/customer application.png"))); // NOI18N
        APLI.add(APLIbg);
        APLIbg.setBounds(0, 0, 800, 400);

        container.add(APLI, "APLI");

        FE.setLayout(null);

        amount3.setBorder(null);
        amount3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount3ActionPerformed(evt);
            }
        });
        FE.add(amount3);
        amount3.setBounds(470, 210, 290, 30);

        name3.setBorder(null);
        FE.add(name3);
        name3.setBounds(80, 160, 310, 30);

        convert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PHP" }));
        convert.setBorder(null);
        FE.add(convert);
        convert.setBounds(470, 160, 290, 30);

        confirm3.setBorderPainted(false);
        confirm3.setContentAreaFilled(false);
        confirm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm3ActionPerformed(evt);
            }
        });
        FE.add(confirm3);
        confirm3.setBounds(410, 360, 100, 30);

        cancel3.setBorderPainted(false);
        cancel3.setContentAreaFilled(false);
        cancel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel3ActionPerformed(evt);
            }
        });
        FE.add(cancel3);
        cancel3.setBounds(300, 360, 100, 30);

        change.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "JPY" }));
        change.setSelectedItem(null);
        change.setBorder(null);
        FE.add(change);
        change.setBounds(150, 210, 240, 30);

        FEbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final Design/customer foreign exchange.png"))); // NOI18N
        FE.add(FEbg);
        FEbg.setBounds(0, 0, 800, 400);

        container.add(FE, "FE");

        queue.setLayout(null);

        queuenum.setFont(new java.awt.Font("Arial Black", 1, 54)); // NOI18N
        queuenum.setForeground(new java.awt.Color(255, 153, 0));
        queuenum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        queuenum.setToolTipText("");
        queue.add(queuenum);
        queuenum.setBounds(260, 150, 270, 150);

        queuebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final Design/queue.png"))); // NOI18N
        queue.add(queuebg);
        queuebg.setBounds(0, 0, 800, 400);

        container.add(queue, "queue");

        getContentPane().add(container);
        container.setBounds(0, 0, 800, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void billsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billsActionPerformed
        
        ((CardLayout)container.getLayout()).show(container, "BP");
    }//GEN-LAST:event_billsActionPerformed

    private void applicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicationActionPerformed
       ((CardLayout)container.getLayout()).show(container, "APLI");
    }//GEN-LAST:event_applicationActionPerformed

    private void exchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exchangeActionPerformed
       ((CardLayout)container.getLayout()).show(container, "FE");
    }//GEN-LAST:event_exchangeActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void bdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdayActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void occupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occupationActionPerformed

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void confirm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm3ActionPerformed
        String enteredName = name3.getText().trim();
    String enteredAmount = amount3.getText().trim();
    String selectedChange = (String) change.getSelectedItem();
    String selectedConvert = (String) convert.getSelectedItem();

    if (enteredName.isEmpty() || enteredAmount.isEmpty() ||
        selectedChange == null || selectedChange.trim().isEmpty() ||
        selectedConvert == null || selectedConvert.trim().isEmpty()) {

        JOptionPane.showMessageDialog(null, "Please fill in all fields", "Input Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }

    // Validate Name
    if (enteredName.length() > 50) {
        JOptionPane.showMessageDialog(null, "Name must be 50 characters or fewer", "Name Error", JOptionPane.ERROR_MESSAGE);
        name3.setText("");
        return;
    }

    if (!enteredName.matches("[a-zA-Z\\s]+")) {
        JOptionPane.showMessageDialog(null, "Name must contain letters only (no numbers or symbols)", "Name Error", JOptionPane.ERROR_MESSAGE);
        name3.setText("");
        return;
    }

    // Validate Amount
    if (!enteredAmount.matches("\\d{1,6}")) {
        JOptionPane.showMessageDialog(null, "Amount must be less than 6 digits and contain numbers only", "Amount Error", JOptionPane.ERROR_MESSAGE);
        amount3.setText("");
        return;
    }

    else {
        double amount = Double.parseDouble(enteredAmount);
        double convertedAmount = 0.0;

        switch (selectedChange.toUpperCase()) {
            case "USD":
                convertedAmount = amount * 56.5;
                break;
            case "EUR":
                convertedAmount = amount * 60.2;
                break;
            case "JPY":
                convertedAmount = amount * 0.38;
                break;
            default:
                convertedAmount = amount; 
        }

        // ✅ Save all details
        QUEUEING.nameFE.add(enteredName);
        QUEUEING.amountFE.add(enteredAmount);
        QUEUEING.changeFE.add(selectedChange);
        QUEUEING.convertFE.add(selectedConvert);
        QUEUEING.conAmountFE.add(String.format("%.2f", convertedAmount)); // formatted
    }

    // Switch to queue panel
    ((CardLayout)container.getLayout()).show(container, "queue");

    int qnum = QUEUEING.counterC++;
    QUEUEING.queueC.add(qnum);
    queuenum.setText("C" + qnum);

    QUEUEING.showCurrentC(); 

    int delay = 5000; // 5 seconds
    Timer timer = new Timer(delay, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            ((CardLayout)container.getLayout()).show(container, "main");
        }
    });

    timer.setRepeats(false);
    timer.start();

    // Reset inputs
    name3.setText(null);
    amount3.setText(null);
    change.setSelectedItem(null);
    convert.setSelectedItem(null);
    }//GEN-LAST:event_confirm3ActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        name.setText(null);
        amount.setText(null);
        paytoOptions.setSelectedItem(null);
        ((CardLayout)container.getLayout()).show(container, "main");
        
    }//GEN-LAST:event_cancelActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
        fname.setText(null);
        number.setText(null);
        address.setText(null);
        bday.setText(null);
        occupation.setText(null);
        email.setText(null);
        ((CardLayout)container.getLayout()).show(container, "main");
    }//GEN-LAST:event_cancel1ActionPerformed

    private void cancel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel3ActionPerformed

        name3.setText(null);
        amount3.setText(null);
        change.setSelectedItem(null);
        convert.setSelectedItem(null);
        ((CardLayout)container.getLayout()).show(container, "main");
    }//GEN-LAST:event_cancel3ActionPerformed

    private void confirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm1ActionPerformed
       
        String fnameVal = fname.getText().trim();
        String numberVal = number.getText().trim();
        String addressVal = address.getText().trim();
        String bdayVal = bday.getText().trim();
        String occupationVal = occupation.getText().trim();
        String emailVal = email.getText().trim();

        if (fnameVal.isEmpty() || numberVal.isEmpty() || addressVal.isEmpty() ||
            bdayVal.isEmpty() || occupationVal.isEmpty() || emailVal.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
//         Validate birthday format MKKK
        if (!bdayVal.matches("\\d{2}/\\d{2}/\\d{4}")) {
        JOptionPane.showMessageDialog(null, "Birthday must be in MM/DD/YYYY format", "Date Format Error", JOptionPane.ERROR_MESSAGE);
        bday.setText(""); // Clear invalid input
        return;
        }  
//        MKKKK
        // Validate number: must start with optional + and followed by 12 digits total
        if (!numberVal.matches("\\+?63\\d{10}")) {
        JOptionPane.showMessageDialog(null, "Contact number must start with +63 or 63 and contain exactly 10 digits after it", "Number Format Error", JOptionPane.ERROR_MESSAGE);
        number.setText(""); // Clear invalid input
        return;
        }
//        Validate Name 
        if (fnameVal.length() > 50) {
        JOptionPane.showMessageDialog(null, "Name must be 50 characters or fewer", "Name Error", JOptionPane.ERROR_MESSAGE);
        fname.setText(""); // Optional: clear the field
        return;
        }
//         ✅ Validate name contains only letters and spaces
        if (!fnameVal.matches("[a-zA-Z\\s]+")) {
            JOptionPane.showMessageDialog(null, "Name must contain letters only (no numbers or symbols)", "Name Error", JOptionPane.ERROR_MESSAGE);
            fname.setText(""); // Optional: clear the field
            return;
        }
//        Validate Occupation
        if (occupationVal.length() > 50) {
        JOptionPane.showMessageDialog(null, "Occupation must be 50 characters or fewer", "Name Error", JOptionPane.ERROR_MESSAGE);
        occupation.setText(""); // Optional: clear the field
        return;
        }
//        ✅ Validate name contains only letters and spaces
        if (!occupationVal.matches("[a-zA-Z\\s]+")) {
            JOptionPane.showMessageDialog(null, "Occupation must contain letters only (no numbers or symbols)", "Name Error", JOptionPane.ERROR_MESSAGE);
            occupation.setText(""); // Optional: clear the field
            return;
        }
        else {
            QUEUEING.nameA.add(fnameVal);
            QUEUEING.numberA.add(numberVal);
            QUEUEING.addressA.add(addressVal);
            QUEUEING.bdayA.add(bdayVal);
            QUEUEING.occupationA.add(occupationVal);
            QUEUEING.emailA.add(emailVal);
}

        ((CardLayout)container.getLayout()).show(container, "queue");
       
        
        int qnum = QUEUEING.counterB++;
        QUEUEING.queueB.add(qnum);
        queuenum.setText("B" + qnum);
        
       
        QUEUEING.showCurrentB(); 
    
        int delay = 5000; // 5 seconds

        Timer timer = new Timer(delay, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ((CardLayout)container.getLayout()).show(container, "main");
                
            }
        });
        
        

        timer.setRepeats(false); 
        timer.start();
        fname.setText(null);
        number.setText(null);
        address.setText(null);
        bday.setText(null);
        occupation.setText(null);
        email.setText(null);
    }//GEN-LAST:event_confirm1ActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        
        String enteredName = name.getText().trim();
        String enteredAmount = amount.getText().trim();
        String selectedPayTo = (String) paytoOptions.getSelectedItem();

        if (enteredName.isEmpty() || enteredAmount.isEmpty() || selectedPayTo == null || selectedPayTo.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        // ✅ Validate name length MKKKK
        if (enteredName.length() > 50) {
            JOptionPane.showMessageDialog(null, "Name must be 50 characters or fewer", "Name Error", JOptionPane.ERROR_MESSAGE);
            name.setText(""); // Optional: clear the field
            return;
        }
//        / ✅ Validate name contains only letters and spaces
        if (!enteredName.matches("[a-zA-Z\\s]+")) {
            JOptionPane.showMessageDialog(null, "Name must contain letters only (no numbers or symbols)", "Name Error", JOptionPane.ERROR_MESSAGE);
            name.setText(""); // Optional: clear the field
            return;
        }
//        MKK AMOUNTT
        if (!enteredAmount.matches("\\d{1,6}")) {
        JOptionPane.showMessageDialog(null, "Amount must be less than 6 digits and contain numbers only", "Amount Error", JOptionPane.ERROR_MESSAGE);
        amount.setText(""); // Clear invalid input
        return;
        } 

        else{
        QUEUEING.nameBP.add(enteredName);
        QUEUEING.payToBP.add(selectedPayTo);
        QUEUEING.amountBP.add(enteredAmount);
        }
            
        int qnum = QUEUEING.counterA++;
        QUEUEING.queueA.add(qnum);
        queuenum.setText("A" + qnum);
        
        QUEUEING.showCurrentA();
       
   ((CardLayout)container.getLayout()).show(container, "queue");
    int delay = 5000;
    Timer timer = new Timer(delay, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            ((CardLayout)container.getLayout()).show(container, "main");
        }
    });
    timer.setRepeats(false); 
    timer.start();
    name.setText(null);
    amount.setText(null);
    paytoOptions.setSelectedItem(null);
    }//GEN-LAST:event_confirmActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void amount3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount3ActionPerformed
 
    /**
     * @param args the command line arguments
     */
   
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CUSTOMER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel APLI;
    private javax.swing.JLabel APLIbg;
    private javax.swing.JPanel BP;
    private javax.swing.JLabel BPbg;
    private javax.swing.JPanel FE;
    private javax.swing.JLabel FEbg;
    private javax.swing.JTextField address;
    private javax.swing.JTextField amount;
    private javax.swing.JTextField amount3;
    private javax.swing.JButton application;
    private javax.swing.JTextField bday;
    private javax.swing.JButton bills;
    private javax.swing.JButton cancel;
    private javax.swing.JButton cancel1;
    private javax.swing.JButton cancel3;
    public static javax.swing.JComboBox<String> change;
    private javax.swing.JButton confirm;
    public static javax.swing.JButton confirm1;
    private javax.swing.JButton confirm3;
    private javax.swing.JPanel container;
    private javax.swing.JComboBox<String> convert;
    private javax.swing.JLabel dashboard;
    private javax.swing.JTextField email;
    private javax.swing.JButton exchange;
    private javax.swing.JTextField fname;
    private javax.swing.JPanel main;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name3;
    private javax.swing.JTextField number;
    private javax.swing.JTextField occupation;
    private javax.swing.JComboBox<String> paytoOptions;
    private javax.swing.JPanel queue;
    private javax.swing.JLabel queuebg;
    private javax.swing.JLabel queuenum;
    // End of variables declaration//GEN-END:variables
}
