/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.queueing;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author lucky
 */
public class DASHBOARD extends javax.swing.JFrame {

    /**
     * Creates new form DASHBOARD
     */
    public DASHBOARD() {
        initComponents();
        convert.setOpaque(false); 
        convert.setBackground(new Color(0, 0, 0, 0)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container1 = new javax.swing.JPanel();
        billsdash = new javax.swing.JPanel();
        application = new javax.swing.JButton();
        exchange = new javax.swing.JButton();
        call = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        next = new javax.swing.JButton();
        pay = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        Bbg = new javax.swing.JLabel();
        applidash = new javax.swing.JPanel();
        billspayment = new javax.swing.JButton();
        exchange1 = new javax.swing.JButton();
        call1 = new javax.swing.JButton();
        cancel1 = new javax.swing.JButton();
        next1 = new javax.swing.JButton();
        number = new javax.swing.JTextField();
        bday = new javax.swing.JTextField();
        name1 = new javax.swing.JTextField();
        confirm1 = new javax.swing.JButton();
        edit1 = new javax.swing.JButton();
        logout1 = new javax.swing.JButton();
        address1 = new javax.swing.JTextField();
        occupation = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        Abg = new javax.swing.JLabel();
        exchangedash = new javax.swing.JPanel();
        billspayment1 = new javax.swing.JButton();
        application2 = new javax.swing.JButton();
        call2 = new javax.swing.JButton();
        cancel2 = new javax.swing.JButton();
        next2 = new javax.swing.JButton();
        change = new javax.swing.JTextField();
        amount3 = new javax.swing.JTextField();
        name2 = new javax.swing.JTextField();
        confirm2 = new javax.swing.JButton();
        edit2 = new javax.swing.JButton();
        logout2 = new javax.swing.JButton();
        convert = new javax.swing.JComboBox<>();
        Abg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 50));
        setUndecorated(true);

        container1.setLayout(new java.awt.CardLayout());

        billsdash.setLayout(null);

        application.setBorderPainted(false);
        application.setContentAreaFilled(false);
        application.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicationActionPerformed(evt);
            }
        });
        billsdash.add(application);
        application.setBounds(10, 227, 140, 30);

        exchange.setBorderPainted(false);
        exchange.setContentAreaFilled(false);
        exchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exchangeActionPerformed(evt);
            }
        });
        billsdash.add(exchange);
        exchange.setBounds(10, 320, 140, 30);

        call.setBorderPainted(false);
        call.setContentAreaFilled(false);
        billsdash.add(call);
        call.setBounds(410, 90, 140, 40);

        cancel.setBorderPainted(false);
        cancel.setContentAreaFilled(false);
        billsdash.add(cancel);
        cancel.setBounds(410, 150, 140, 40);

        next.setBorderPainted(false);
        next.setContentAreaFilled(false);
        billsdash.add(next);
        next.setBounds(410, 30, 140, 50);

        pay.setBackground(new java.awt.Color(255, 255, 255));
        pay.setBorder(null);
        pay.setEnabled(false);
        billsdash.add(pay);
        pay.setBounds(270, 380, 330, 20);

        amount.setBackground(new java.awt.Color(255, 255, 255));
        amount.setBorder(null);
        amount.setEnabled(false);
        billsdash.add(amount);
        amount.setBounds(280, 430, 320, 20);

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setBorder(null);
        name.setEnabled(false);
        billsdash.add(name);
        name.setBounds(270, 330, 330, 20);

        confirm.setBorderPainted(false);
        confirm.setContentAreaFilled(false);
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        billsdash.add(confirm);
        confirm.setBounds(410, 500, 90, 20);

        edit.setBorderPainted(false);
        edit.setContentAreaFilled(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        billsdash.add(edit);
        edit.setBounds(300, 497, 90, 30);

        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        billsdash.add(logout);
        logout.setBounds(30, 510, 100, 20);
        billsdash.add(Bbg);
        Bbg.setBounds(-5, 0, 900, 0);

        container1.add(billsdash, "BDASH");

        applidash.setLayout(null);

        billspayment.setBorderPainted(false);
        billspayment.setContentAreaFilled(false);
        billspayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billspaymentActionPerformed(evt);
            }
        });
        applidash.add(billspayment);
        billspayment.setBounds(10, 130, 140, 30);

        exchange1.setBorderPainted(false);
        exchange1.setContentAreaFilled(false);
        exchange1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exchange1ActionPerformed(evt);
            }
        });
        applidash.add(exchange1);
        exchange1.setBounds(10, 320, 140, 30);

        call1.setBorderPainted(false);
        call1.setContentAreaFilled(false);
        applidash.add(call1);
        call1.setBounds(410, 90, 140, 40);

        cancel1.setBorderPainted(false);
        cancel1.setContentAreaFilled(false);
        applidash.add(cancel1);
        cancel1.setBounds(410, 150, 140, 40);

        next1.setBorderPainted(false);
        next1.setContentAreaFilled(false);
        applidash.add(next1);
        next1.setBounds(410, 30, 140, 50);

        number.setBackground(new java.awt.Color(255, 255, 255));
        number.setBorder(null);
        number.setEnabled(false);
        applidash.add(number);
        number.setBounds(270, 370, 250, 20);

        bday.setBackground(new java.awt.Color(255, 255, 255));
        bday.setBorder(null);
        bday.setEnabled(false);
        bday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdayActionPerformed(evt);
            }
        });
        applidash.add(bday);
        bday.setBounds(270, 470, 250, 20);

        name1.setBackground(new java.awt.Color(255, 255, 255));
        name1.setBorder(null);
        name1.setEnabled(false);
        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        applidash.add(name1);
        name1.setBounds(270, 320, 250, 20);

        confirm1.setBorderPainted(false);
        confirm1.setContentAreaFilled(false);
        applidash.add(confirm1);
        confirm1.setBounds(700, 420, 100, 20);

        edit1.setBorderPainted(false);
        edit1.setContentAreaFilled(false);
        edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit1ActionPerformed(evt);
            }
        });
        applidash.add(edit1);
        edit1.setBounds(600, 420, 90, 20);

        logout1.setBorderPainted(false);
        logout1.setContentAreaFilled(false);
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });
        applidash.add(logout1);
        logout1.setBounds(30, 510, 100, 20);

        address1.setBackground(new java.awt.Color(255, 255, 255));
        address1.setBorder(null);
        address1.setEnabled(false);
        address1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address1ActionPerformed(evt);
            }
        });
        applidash.add(address1);
        address1.setBounds(270, 420, 250, 20);

        occupation.setBackground(new java.awt.Color(255, 255, 255));
        occupation.setEnabled(false);
        applidash.add(occupation);
        occupation.setBounds(620, 320, 230, 22);

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setEnabled(false);
        applidash.add(email);
        email.setBounds(630, 370, 220, 22);
        applidash.add(Abg);
        Abg.setBounds(-5, 0, 900, 0);

        container1.add(applidash, "ADASH");

        exchangedash.setLayout(null);

        billspayment1.setBorderPainted(false);
        billspayment1.setContentAreaFilled(false);
        billspayment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billspayment1ActionPerformed(evt);
            }
        });
        exchangedash.add(billspayment1);
        billspayment1.setBounds(10, 130, 140, 30);

        application2.setBorderPainted(false);
        application2.setContentAreaFilled(false);
        application2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                application2ActionPerformed(evt);
            }
        });
        exchangedash.add(application2);
        application2.setBounds(10, 230, 140, 30);

        call2.setBorderPainted(false);
        call2.setContentAreaFilled(false);
        exchangedash.add(call2);
        call2.setBounds(410, 90, 140, 40);

        cancel2.setBorderPainted(false);
        cancel2.setContentAreaFilled(false);
        exchangedash.add(cancel2);
        cancel2.setBounds(410, 150, 140, 40);

        next2.setBorderPainted(false);
        next2.setContentAreaFilled(false);
        exchangedash.add(next2);
        next2.setBounds(410, 30, 140, 50);

        change.setBackground(new java.awt.Color(255, 255, 255));
        change.setBorder(null);
        exchangedash.add(change);
        change.setBounds(320, 370, 240, 20);

        amount3.setBackground(new java.awt.Color(255, 255, 255));
        amount3.setBorder(null);
        amount3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount3ActionPerformed(evt);
            }
        });
        exchangedash.add(amount3);
        amount3.setBounds(270, 470, 290, 20);

        name2.setBackground(new java.awt.Color(255, 255, 255));
        name2.setBorder(null);
        exchangedash.add(name2);
        name2.setBounds(270, 320, 290, 20);

        confirm2.setBorderPainted(false);
        confirm2.setContentAreaFilled(false);
        exchangedash.add(confirm2);
        confirm2.setBounds(390, 500, 90, 30);

        edit2.setBorderPainted(false);
        edit2.setContentAreaFilled(false);
        edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit2ActionPerformed(evt);
            }
        });
        exchangedash.add(edit2);
        edit2.setBounds(280, 500, 100, 30);

        logout2.setBorderPainted(false);
        logout2.setContentAreaFilled(false);
        logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout2ActionPerformed(evt);
            }
        });
        exchangedash.add(logout2);
        logout2.setBounds(30, 510, 100, 20);

        convert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        convert.setEnabled(false);
        exchangedash.add(convert);
        convert.setBounds(270, 416, 290, 30);
        exchangedash.add(Abg1);
        Abg1.setBounds(-5, 0, 900, 0);

        container1.add(exchangedash, "EDASH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container1, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdayActionPerformed

    private void address1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address1ActionPerformed

    private void amount3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount3ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        
        
        int option = JOptionPane.showConfirmDialog(null,"Are you sure you want to logout?","Logout?",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        
        if (option == JOptionPane.OK_OPTION) {
            this.setVisible(false);
            new EMPLOYEE().setVisible(true);
            new TV().setVisible(false);
            new CUSTOMER().setVisible(false);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void applicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicationActionPerformed
        ((CardLayout)container1.getLayout()).show(container1, "ADASH");
    }//GEN-LAST:event_applicationActionPerformed

    private void exchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exchangeActionPerformed
        ((CardLayout)container1.getLayout()).show(container1, "EDASH");
    }//GEN-LAST:event_exchangeActionPerformed

    private void billspaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billspaymentActionPerformed
        ((CardLayout)container1.getLayout()).show(container1, "BDASH");
    }//GEN-LAST:event_billspaymentActionPerformed

    private void exchange1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exchange1ActionPerformed
        ((CardLayout)container1.getLayout()).show(container1, "EDASH");
    }//GEN-LAST:event_exchange1ActionPerformed

    private void application2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_application2ActionPerformed
        ((CardLayout)container1.getLayout()).show(container1, "ADASH");
    }//GEN-LAST:event_application2ActionPerformed

    private void billspayment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billspayment1ActionPerformed
        ((CardLayout)container1.getLayout()).show(container1, "EDASH");
    }//GEN-LAST:event_billspayment1ActionPerformed

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
        
        int option = JOptionPane.showConfirmDialog(null,"Are you sure you want to logout?","Logout?",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        
        if (option == JOptionPane.OK_OPTION) {
            this.setVisible(false);
            new EMPLOYEE().setVisible(true);
            new TV().setVisible(false);
            new CUSTOMER().setVisible(false);
        }
    }//GEN-LAST:event_logout1ActionPerformed

    private void logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout2ActionPerformed
        
        int option = JOptionPane.showConfirmDialog(null,"Are you sure you want to logout?","Logout?",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        
        if (option == JOptionPane.OK_OPTION) {
            this.setVisible(false);
            new EMPLOYEE().setVisible(true);
            new TV().setVisible(false);
            new CUSTOMER().setVisible(false);
        }
    }//GEN-LAST:event_logout2ActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        name.setEnabled(true);
        pay.setEnabled(true);
        amount.setEnabled(true);
    }//GEN-LAST:event_editActionPerformed

    private void edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit1ActionPerformed
        name1.setEnabled(true);
        number.setEnabled(true);
        address1.setEnabled(true);
        bday.setEnabled(true);
        occupation.setEnabled(true);
        email.setEnabled(true);
    }//GEN-LAST:event_edit1ActionPerformed

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void edit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit2ActionPerformed
        name2.setEnabled(true);
        change.setEnabled(true);
        amount.setEnabled(true);
        convert.setEnabled(true);
    }//GEN-LAST:event_edit2ActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        while (true) {
        String enteredName = name.getText().trim();
        String enteredPay = pay.getText().trim();
        String enteredAmount = amount.getText().trim();

        if (enteredName.isEmpty() || enteredPay.isEmpty() || enteredAmount.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields: Name, Pay To, and Amount", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit the method and wait for user to re-trigger the event after correcting inputs
        } else {
            break; // Input is valid; continue with the rest of the code
        }
    }
    }//GEN-LAST:event_confirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DASHBOARD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Abg;
    private javax.swing.JLabel Abg1;
    private javax.swing.JLabel Bbg;
    private javax.swing.JTextField address1;
    private javax.swing.JTextField amount;
    private javax.swing.JTextField amount3;
    private javax.swing.JButton application;
    private javax.swing.JButton application2;
    private javax.swing.JPanel applidash;
    private javax.swing.JTextField bday;
    private javax.swing.JPanel billsdash;
    private javax.swing.JButton billspayment;
    private javax.swing.JButton billspayment1;
    private javax.swing.JButton call;
    private javax.swing.JButton call1;
    private javax.swing.JButton call2;
    private javax.swing.JButton cancel;
    private javax.swing.JButton cancel1;
    private javax.swing.JButton cancel2;
    private javax.swing.JTextField change;
    private javax.swing.JButton confirm;
    private javax.swing.JButton confirm1;
    private javax.swing.JButton confirm2;
    private javax.swing.JPanel container1;
    private javax.swing.JComboBox<String> convert;
    private javax.swing.JButton edit;
    private javax.swing.JButton edit1;
    private javax.swing.JButton edit2;
    private javax.swing.JTextField email;
    private javax.swing.JButton exchange;
    private javax.swing.JButton exchange1;
    private javax.swing.JPanel exchangedash;
    private javax.swing.JButton logout;
    private javax.swing.JButton logout1;
    private javax.swing.JButton logout2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField name2;
    private javax.swing.JButton next;
    private javax.swing.JButton next1;
    private javax.swing.JButton next2;
    private javax.swing.JTextField number;
    private javax.swing.JTextField occupation;
    private javax.swing.JTextField pay;
    // End of variables declaration//GEN-END:variables
}
