/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.queueing;

import static com.mycompany.queueing.QUEUEING.queueA;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import javax.swing.Timer;

//

/**
 *
 * @author lucky
 */
public class DASHBOARD extends javax.swing.JFrame {

   

    /**
     * Creates new form DASHBOARD
     */
    public DASHBOARD() {
        initComponents();
        

        convert.setOpaque(false); 
        convert.setBackground(new Color(0, 0, 0, 0)); 
        pay.setOpaque(false); 
        pay.setEnabled(false);
        change.setEnabled(false);
        bday.setBackground(new Color(0, 0, 0, 0));
        pay.setBackground(new Color(0, 0, 0, 0)); 
        change.setBackground(new Color(0, 0, 0, 0)); 
        recallA.setBackground(new Color(0, 0, 0, 0)); 
        holdA.setBackground(new Color(0, 0, 0, 0)); 
        recallB.setBackground(new Color(0, 0, 0, 0)); 
        holdB.setBackground(new Color(0, 0, 0, 0)); 
        recallC.setBackground(new Color(0, 0, 0, 0)); 
        holdC.setBackground(new Color(0, 0, 0, 0)); 
        holdListA.setBackground(new Color(0, 0, 0, 0)); 
        holdListA.setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        holdListA.setEditable(false);
        holdListB.setBackground(new Color(0, 0, 0, 0)); 
        holdListB.setOpaque(false);
        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
        holdListB.setEditable(false);
        holdListC.setBackground(new Color(0, 0, 0, 0)); 
        holdListC.setOpaque(false);
        jScrollPane3.setOpaque(false);
        jScrollPane3.getViewport().setOpaque(false);
        holdListC.setEditable(false);
       
        
        //edit ng amount sa fe
        amount3.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
                public void insertUpdate(javax.swing.event.DocumentEvent e) { QUEUEING.updateConversion(); }
                public void removeUpdate(javax.swing.event.DocumentEvent e) { QUEUEING.updateConversion(); }
                public void changedUpdate(javax.swing.event.DocumentEvent e) { QUEUEING.updateConversion(); }
            });

           
            change.addActionListener(e -> QUEUEING.updateConversion());       
            
            
   }
   
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container1 = new javax.swing.JPanel();
        billsdash = new javax.swing.JPanel();
        application = new javax.swing.JButton();
        exchange = new javax.swing.JButton();
        call = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        amount = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        pay = new javax.swing.JComboBox<>();
        inQueueA = new javax.swing.JLabel();
        serveA = new javax.swing.JLabel();
        noOfServedA = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        holdListA = new javax.swing.JTextArea();
        recallA = new javax.swing.JButton();
        holdA = new javax.swing.JButton();
        AmountReceived = new javax.swing.JTextField();
        Bbg = new javax.swing.JLabel();
        applidash = new javax.swing.JPanel();
        billspayment = new javax.swing.JButton();
        exchange1 = new javax.swing.JButton();
        call1 = new javax.swing.JButton();
        cancel1 = new javax.swing.JButton();
        number = new javax.swing.JTextField();
        name1 = new javax.swing.JTextField();
        confirm1 = new javax.swing.JButton();
        edit1 = new javax.swing.JButton();
        logout1 = new javax.swing.JButton();
        address1 = new javax.swing.JTextField();
        occupation = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        bday = new com.toedter.calendar.JDateChooser();
        inQueueB = new javax.swing.JLabel();
        serveB = new javax.swing.JLabel();
        recallB = new javax.swing.JButton();
        holdB = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        holdListB = new javax.swing.JTextArea();
        noOfServedB = new javax.swing.JLabel();
        Abg = new javax.swing.JLabel();
        exchangedash = new javax.swing.JPanel();
        billspayment1 = new javax.swing.JButton();
        application2 = new javax.swing.JButton();
        call2 = new javax.swing.JButton();
        cancel2 = new javax.swing.JButton();
        conAmount = new javax.swing.JTextField();
        amount3 = new javax.swing.JTextField();
        name2 = new javax.swing.JTextField();
        confirm2 = new javax.swing.JButton();
        edit2 = new javax.swing.JButton();
        logout2 = new javax.swing.JButton();
        convert = new javax.swing.JComboBox<>();
        change = new javax.swing.JComboBox<>();
        inQueueC = new javax.swing.JLabel();
        serveC = new javax.swing.JLabel();
        holdC = new javax.swing.JButton();
        recallC = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        holdListC = new javax.swing.JTextArea();
        noOfServedC = new javax.swing.JLabel();
        Abg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 50));
        setMinimumSize(new java.awt.Dimension(891, 546));
        setUndecorated(true);
        getContentPane().setLayout(null);

        container1.setLayout(new java.awt.CardLayout());

        billsdash.setLayout(null);

        application.setBorderPainted(false);
        application.setContentAreaFilled(false);
        application.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicationActionPerformed(evt);
            }
        });
        billsdash.add(application);
        application.setBounds(10, 227, 140, 30);

        exchange.setBorderPainted(false);
        exchange.setContentAreaFilled(false);
        exchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exchangeActionPerformed(evt);
            }
        });
        billsdash.add(exchange);
        exchange.setBounds(10, 320, 140, 30);

        call.setBorderPainted(false);
        call.setContentAreaFilled(false);
        call.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callActionPerformed(evt);
            }
        });
        billsdash.add(call);
        call.setBounds(410, 20, 140, 40);

        cancel.setBorderPainted(false);
        cancel.setContentAreaFilled(false);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        billsdash.add(cancel);
        cancel.setBounds(410, 160, 140, 50);

        amount.setBackground(new java.awt.Color(255, 255, 255));
        amount.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        amount.setEnabled(false);
        amount.setOpaque(true);
        billsdash.add(amount);
        amount.setBounds(280, 400, 310, 20);

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        name.setCaretColor(new java.awt.Color(255, 255, 255));
        name.setEnabled(false);
        name.setOpaque(true);
        billsdash.add(name);
        name.setBounds(270, 300, 310, 20);

        confirm.setBorderPainted(false);
        confirm.setContentAreaFilled(false);
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        billsdash.add(confirm);
        confirm.setBounds(410, 500, 90, 20);

        edit.setBorderPainted(false);
        edit.setContentAreaFilled(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        billsdash.add(edit);
        edit.setBounds(300, 497, 90, 30);

        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        billsdash.add(logout);
        logout.setBounds(30, 510, 100, 30);

        pay.setBackground(new java.awt.Color(255, 255, 255));
        pay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maynilad", "Meralco", "Globe", "PLDT", "Smart" }));
        pay.setSelectedItem(null);
        pay.setBorder(null);
        pay.setEnabled(false);
        billsdash.add(pay);
        pay.setBounds(280, 340, 310, 40);

        inQueueA.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        inQueueA.setForeground(new java.awt.Color(255, 153, 0));
        inQueueA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billsdash.add(inQueueA);
        inQueueA.setBounds(620, 160, 50, 50);

        serveA.setFont(new java.awt.Font("Arial Black", 1, 54)); // NOI18N
        serveA.setForeground(new java.awt.Color(255, 153, 0));
        serveA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billsdash.add(serveA);
        serveA.setBounds(220, 70, 140, 120);

        noOfServedA.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        noOfServedA.setForeground(new java.awt.Color(255, 153, 0));
        noOfServedA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billsdash.add(noOfServedA);
        noOfServedA.setBounds(620, 60, 50, 50);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setEnabled(false);

        holdListA.setEditable(false);
        holdListA.setColumns(20);
        holdListA.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        holdListA.setForeground(new java.awt.Color(255, 153, 0));
        holdListA.setRows(5);
        holdListA.setBorder(null);
        holdListA.setOpaque(false);
        jScrollPane1.setViewportView(holdListA);

        billsdash.add(jScrollPane1);
        jScrollPane1.setBounds(780, 60, 70, 140);

        recallA.setContentAreaFilled(false);
        recallA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recallAActionPerformed(evt);
            }
        });
        billsdash.add(recallA);
        recallA.setBounds(410, 110, 140, 50);

        holdA.setContentAreaFilled(false);
        holdA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holdAActionPerformed(evt);
            }
        });
        billsdash.add(holdA);
        holdA.setBounds(410, 60, 140, 50);

        AmountReceived.setBackground(new java.awt.Color(255, 255, 255));
        AmountReceived.setBorder(null);
        billsdash.add(AmountReceived);
        AmountReceived.setBounds(340, 446, 250, 30);

        Bbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final Design/bills payment dashboard.png"))); // NOI18N
        billsdash.add(Bbg);
        Bbg.setBounds(-5, 0, 900, 550);

        container1.add(billsdash, "BDASH");

        applidash.setEnabled(false);
        applidash.setLayout(null);

        billspayment.setBorderPainted(false);
        billspayment.setContentAreaFilled(false);
        billspayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billspaymentActionPerformed(evt);
            }
        });
        applidash.add(billspayment);
        billspayment.setBounds(10, 130, 140, 30);

        exchange1.setBorderPainted(false);
        exchange1.setContentAreaFilled(false);
        exchange1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exchange1ActionPerformed(evt);
            }
        });
        applidash.add(exchange1);
        exchange1.setBounds(10, 320, 140, 30);

        call1.setBorderPainted(false);
        call1.setContentAreaFilled(false);
        call1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                call1ActionPerformed(evt);
            }
        });
        applidash.add(call1);
        call1.setBounds(410, 20, 140, 40);

        cancel1.setBorderPainted(false);
        cancel1.setContentAreaFilled(false);
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });
        applidash.add(cancel1);
        cancel1.setBounds(410, 160, 140, 50);

        number.setBackground(new java.awt.Color(255, 255, 255));
        number.setBorder(null);
        number.setEnabled(false);
        applidash.add(number);
        number.setBounds(270, 370, 250, 20);

        name1.setBackground(new java.awt.Color(255, 255, 255));
        name1.setBorder(null);
        name1.setEnabled(false);
        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        applidash.add(name1);
        name1.setBounds(270, 320, 250, 20);

        confirm1.setBorderPainted(false);
        confirm1.setContentAreaFilled(false);
        confirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm1ActionPerformed(evt);
            }
        });
        applidash.add(confirm1);
        confirm1.setBounds(700, 420, 100, 20);

        edit1.setBorderPainted(false);
        edit1.setContentAreaFilled(false);
        edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit1ActionPerformed(evt);
            }
        });
        applidash.add(edit1);
        edit1.setBounds(600, 420, 90, 20);

        logout1.setBorderPainted(false);
        logout1.setContentAreaFilled(false);
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });
        applidash.add(logout1);
        logout1.setBounds(30, 510, 100, 20);

        address1.setBackground(new java.awt.Color(255, 255, 255));
        address1.setBorder(null);
        address1.setEnabled(false);
        address1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address1ActionPerformed(evt);
            }
        });
        applidash.add(address1);
        address1.setBounds(270, 420, 250, 20);

        occupation.setBackground(new java.awt.Color(255, 255, 255));
        occupation.setBorder(null);
        occupation.setEnabled(false);
        applidash.add(occupation);
        occupation.setBounds(620, 320, 230, 20);

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setBorder(null);
        email.setEnabled(false);
        applidash.add(email);
        email.setBounds(630, 370, 220, 20);

        bday.setEnabled(false);
        applidash.add(bday);
        bday.setBounds(260, 470, 260, 22);

        inQueueB.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        inQueueB.setForeground(new java.awt.Color(255, 153, 0));
        applidash.add(inQueueB);
        inQueueB.setBounds(620, 160, 50, 50);

        serveB.setFont(new java.awt.Font("Arial Black", 1, 54)); // NOI18N
        serveB.setForeground(new java.awt.Color(255, 153, 0));
        serveB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        applidash.add(serveB);
        serveB.setBounds(220, 70, 140, 120);

        recallB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recallBActionPerformed(evt);
            }
        });
        applidash.add(recallB);
        recallB.setBounds(410, 110, 140, 50);

        holdB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holdBActionPerformed(evt);
            }
        });
        applidash.add(holdB);
        holdB.setBounds(410, 60, 140, 50);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setEnabled(false);

        holdListB.setEditable(false);
        holdListB.setColumns(20);
        holdListB.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        holdListB.setForeground(new java.awt.Color(255, 153, 0));
        holdListB.setRows(5);
        holdListB.setBorder(null);
        holdListB.setOpaque(false);
        jScrollPane2.setViewportView(holdListB);

        applidash.add(jScrollPane2);
        jScrollPane2.setBounds(790, 60, 70, 140);

        noOfServedB.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        noOfServedB.setForeground(new java.awt.Color(255, 153, 0));
        noOfServedB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        applidash.add(noOfServedB);
        noOfServedB.setBounds(620, 60, 50, 50);

        Abg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final Design/application dashboard.png"))); // NOI18N
        applidash.add(Abg);
        Abg.setBounds(-5, 0, 900, 550);

        container1.add(applidash, "ADASH");

        exchangedash.setLayout(null);

        billspayment1.setBorderPainted(false);
        billspayment1.setContentAreaFilled(false);
        billspayment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billspayment1ActionPerformed(evt);
            }
        });
        exchangedash.add(billspayment1);
        billspayment1.setBounds(10, 130, 140, 40);

        application2.setBorderPainted(false);
        application2.setContentAreaFilled(false);
        application2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                application2ActionPerformed(evt);
            }
        });
        exchangedash.add(application2);
        application2.setBounds(10, 230, 140, 30);

        call2.setBorderPainted(false);
        call2.setContentAreaFilled(false);
        call2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                call2ActionPerformed(evt);
            }
        });
        exchangedash.add(call2);
        call2.setBounds(410, 20, 140, 40);

        cancel2.setBorderPainted(false);
        cancel2.setContentAreaFilled(false);
        cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel2ActionPerformed(evt);
            }
        });
        exchangedash.add(cancel2);
        cancel2.setBounds(410, 160, 140, 50);

        conAmount.setEditable(false);
        conAmount.setBackground(new java.awt.Color(255, 255, 255));
        conAmount.setBorder(null);
        conAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conAmountActionPerformed(evt);
            }
        });
        exchangedash.add(conAmount);
        conAmount.setBounds(660, 420, 210, 30);

        amount3.setBackground(new java.awt.Color(255, 255, 255));
        amount3.setBorder(null);
        amount3.setEnabled(false);
        amount3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount3ActionPerformed(evt);
            }
        });
        exchangedash.add(amount3);
        amount3.setBounds(610, 370, 260, 30);

        name2.setBackground(new java.awt.Color(255, 255, 255));
        name2.setBorder(null);
        name2.setEnabled(false);
        exchangedash.add(name2);
        name2.setBounds(240, 320, 270, 30);

        confirm2.setBorderPainted(false);
        confirm2.setContentAreaFilled(false);
        confirm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm2ActionPerformed(evt);
            }
        });
        exchangedash.add(confirm2);
        confirm2.setBounds(540, 480, 90, 30);

        edit2.setBorderPainted(false);
        edit2.setContentAreaFilled(false);
        edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit2ActionPerformed(evt);
            }
        });
        exchangedash.add(edit2);
        edit2.setBounds(430, 480, 100, 30);

        logout2.setBorderPainted(false);
        logout2.setContentAreaFilled(false);
        logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout2ActionPerformed(evt);
            }
        });
        exchangedash.add(logout2);
        logout2.setBounds(30, 510, 100, 20);

        convert.setBackground(new java.awt.Color(255, 255, 255));
        convert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PHP", " " }));
        convert.setBorder(null);
        convert.setEnabled(false);
        exchangedash.add(convert);
        convert.setBounds(260, 420, 250, 30);

        change.setBackground(new java.awt.Color(255, 255, 255));
        change.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EUR", "JPY", " " }));
        change.setBorder(null);
        change.setEnabled(false);
        exchangedash.add(change);
        change.setBounds(310, 370, 200, 30);

        inQueueC.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        inQueueC.setForeground(new java.awt.Color(255, 153, 0));
        exchangedash.add(inQueueC);
        inQueueC.setBounds(620, 160, 50, 50);

        serveC.setFont(new java.awt.Font("Arial Black", 1, 54)); // NOI18N
        serveC.setForeground(new java.awt.Color(255, 153, 0));
        serveC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exchangedash.add(serveC);
        serveC.setBounds(220, 70, 140, 120);

        holdC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holdCActionPerformed(evt);
            }
        });
        exchangedash.add(holdC);
        holdC.setBounds(410, 70, 140, 40);

        recallC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recallCActionPerformed(evt);
            }
        });
        exchangedash.add(recallC);
        recallC.setBounds(410, 120, 140, 40);

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setEnabled(false);

        holdListC.setEditable(false);
        holdListC.setColumns(20);
        holdListC.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        holdListC.setForeground(new java.awt.Color(255, 153, 0));
        holdListC.setRows(5);
        holdListC.setBorder(null);
        holdListC.setOpaque(false);
        jScrollPane3.setViewportView(holdListC);

        exchangedash.add(jScrollPane3);
        jScrollPane3.setBounds(780, 60, 70, 140);

        noOfServedC.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        noOfServedC.setForeground(new java.awt.Color(255, 153, 0));
        noOfServedC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exchangedash.add(noOfServedC);
        noOfServedC.setBounds(620, 60, 50, 50);

        Abg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final Design/foreign ex dashboard.png"))); // NOI18N
        exchangedash.add(Abg1);
        Abg1.setBounds(-5, 0, 900, 550);

        container1.add(exchangedash, "EDASH");

        getContentPane().add(container1);
        container1.setBounds(0, 0, 893, 548);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void address1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address1ActionPerformed

    private void amount3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount3ActionPerformed

    private void billspaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billspaymentActionPerformed
        ((CardLayout)container1.getLayout()).show(container1, "BDASH");
    }//GEN-LAST:event_billspaymentActionPerformed

    private void exchange1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exchange1ActionPerformed
        ((CardLayout)container1.getLayout()).show(container1, "EDASH");
    }//GEN-LAST:event_exchange1ActionPerformed

    private void application2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_application2ActionPerformed
        ((CardLayout)container1.getLayout()).show(container1, "ADASH");
    }//GEN-LAST:event_application2ActionPerformed

    private void billspayment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billspayment1ActionPerformed
        ((CardLayout)container1.getLayout()).show(container1, "BDASH");
    }//GEN-LAST:event_billspayment1ActionPerformed

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
        
         int option = JOptionPane.showConfirmDialog(null,"Are you sure you want to logout?","Logout?",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        
         if (option == JOptionPane.OK_OPTION) {
        // Dispose all open windows
        for (java.awt.Window w : java.awt.Window.getWindows()) {
            w.setVisible(false);
        }

        // Show login again
        new EMPLOYEE().setVisible(true);
    }
    }//GEN-LAST:event_logout1ActionPerformed

    private void logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout2ActionPerformed
        
         int option = JOptionPane.showConfirmDialog(null,"Are you sure you want to logout?","Logout?",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        
            if (option == JOptionPane.OK_OPTION) {
           // Dispose all open windows
           for (java.awt.Window w : java.awt.Window.getWindows()) {
                w.setVisible(false);
           }

           // Show login again
           new EMPLOYEE().setVisible(true);
       }
    }//GEN-LAST:event_logout2ActionPerformed

    private void edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit1ActionPerformed
        name1.setEnabled(true);
        number.setEnabled(true);
        address1.setEnabled(true);
        bday.setEnabled(true);
        occupation.setEnabled(true);
        email.setEnabled(true);
    }//GEN-LAST:event_edit1ActionPerformed

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void edit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit2ActionPerformed
        name2.setEnabled(true);
        change.setEnabled(true);
        amount3.setEnabled(true);
        convert.setEnabled(true);
        
    }//GEN-LAST:event_edit2ActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
         //APPLICATION
        if (QUEUEING.queueC.isEmpty()) {
            JOptionPane.showMessageDialog(null, "The queue is empty!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Integer servedNum = QUEUEING.queueB.poll();
            if (servedNum != null) {
                int index = servedNum - 1; 
                QUEUEING.showCurrentB();
            } else {
                serveB.setText(null);
                TV.serveB.setText(null);
                name1.setText("");
                number.setText("");
                address1.setText("");
                bday.setDate(null);
                occupation.setText("");
                email.setText("");
            }
        }
    }//GEN-LAST:event_cancel1ActionPerformed

    private void cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel2ActionPerformed
       //FOREIGN EXCHANGE
        if (QUEUEING.queueC.isEmpty()) {
            JOptionPane.showMessageDialog(null, "The queue is empty!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Integer servedNum = QUEUEING.queueC.poll();
            if (servedNum != null) {
                int index = servedNum - 1;
                QUEUEING.showCurrentC();
            } else {
                serveC.setText(null);
                TV.serveC.setText(null);
                name2.setText("");
                convert.setSelectedItem("");
                amount3.setText("");
            }
}
    }//GEN-LAST:event_cancel2ActionPerformed

    private void confirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm1ActionPerformed
                                       
        String fullname = name1.getText().trim();
        String num = number.getText().trim();
        Date selectedDate = bday.getDate(); 
        String add = address1.getText().trim();
        String occu = occupation.getText().trim();
        String ema = email.getText().trim();

        // Validation
        if (fullname.isEmpty() && num.isEmpty() && selectedDate == null 
                && add.isEmpty() && occu.isEmpty() && ema.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
        } 
        if (fullname.isEmpty() || !fullname.matches("[a-zA-Z\\s]+") || fullname.length() > 50) {
            JOptionPane.showMessageDialog(null, "Name must be letters only and max 50 chars", "Name Error", JOptionPane.ERROR_MESSAGE);
            name1.setText("");
            return;
        }
        if (num.isEmpty() || !num.matches("\\+63\\d{10}")) {
            JOptionPane.showMessageDialog(null, "Contact number must start with +63 and contain exactly 10 digits after it", "Number Error", JOptionPane.ERROR_MESSAGE);
            number.setText("+63"); 
            return;
        }
        if (selectedDate == null) {
            JOptionPane.showMessageDialog(null, "Please select your Birthday", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (add.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input your Address", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (occu.isEmpty() || !occu.matches("[a-zA-Z\\s]+") || occu.length() > 50) {
            JOptionPane.showMessageDialog(null, "Occupation must be letters only and max 50 chars", "Occupation Error", JOptionPane.ERROR_MESSAGE);
            occupation.setText("");
            return;
        }
        if (ema.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input your Email", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Confirm dialog
        int c = JOptionPane.showConfirmDialog(null, "Are you sure the information is correct?", "Confirmation", JOptionPane.OK_CANCEL_OPTION);
        if (c != JOptionPane.OK_OPTION) return;

        // Format birthday
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        String bda = sdf.format(selectedDate);

        // Update queue data
        Integer servedNum = QUEUEING.queueB.peek(); 
        if (servedNum != null) {
            int index = servedNum - 1;
            if (index >= 0 && index < QUEUEING.nameA.size()) {
                QUEUEING.nameA.set(index, fullname);
                QUEUEING.numberA.set(index, num);
                QUEUEING.bdayA.set(index, bda);   
                QUEUEING.addressA.set(index, add);
                QUEUEING.occupationA.set(index, occu);
                QUEUEING.emailA.set(index, ema);
            }
        }

        // Generate OTP
        final String[] otp = { String.format("%06d", new java.util.Random().nextInt(999999)) };
        OTPCustomer otpFrame = new OTPCustomer();
        otpFrame.OTPText.setText(otp[0]);
        otpFrame.setVisible(true);

        OTPEmployee employeeFrame = new OTPEmployee();
        employeeFrame.setVisible(true);

        final int[] attempts = {0};
        employeeFrame.enter.addActionListener(e -> {
            String enteredOTP = employeeFrame.OTPConfirmation.getText().trim();
            if (enteredOTP.equals(otp[0])) {
                JOptionPane.showMessageDialog(null, "OTP Verified! Proceeding...", "Success", JOptionPane.INFORMATION_MESSAGE);
                otpFrame.dispose();
                employeeFrame.dispose();

                // Show Card first
                Card cardFrame = new Card();
                QUEUEING.card(); // generate card number
                cardFrame.setVisible(true);
                new javax.swing.Timer(6000, ev -> cardFrame.dispose()).start();

                // Then show Receipt
                TICKET ticketFrame = new TICKET();
                ticketFrame.setVisible(true);
                new javax.swing.Timer(5000, ev -> ticketFrame.dispose()).start();

                QUEUEING.printReceiptB();

                // Disable fields after confirmation
                name1.setEnabled(false);
                number.setEnabled(false);
                bday.setEnabled(false);
                address1.setEnabled(false);
                occupation.setEnabled(false);
                email.setEnabled(false);

                Integer sn = QUEUEING.queueB.poll();
                if (sn != null) {
                    QUEUEING.showCurrentB();
                    QUEUEING.servedCountB++;
                    noOfServedB.setText(String.valueOf(QUEUEING.servedCountB));
                } else {
                    serveB.setText(null);
                    TV.serveB.setText(null);
                    name1.setText("");
                    number.setText("+63");
                    address1.setText("");
                    bday.setDate(null); 
                    occupation.setText("");
                    email.setText("");
                }

            } else {
                attempts[0]++;
                if (attempts[0] < 3) {
                    JOptionPane.showMessageDialog(null, "Invalid OTP. Try again! (" + attempts[0] + "/3)", "Error", JOptionPane.ERROR_MESSAGE);
                    employeeFrame.OTPConfirmation.setText("");
                } else {
                    otp[0] = String.format("%06d", new java.util.Random().nextInt(999999));
                    otpFrame.OTPText.setText(otp[0]);
                    JOptionPane.showMessageDialog(null, "Maximum attempts reached. A new OTP has been generated.", "New OTP", JOptionPane.INFORMATION_MESSAGE);
                    attempts[0] = 0;
                    employeeFrame.OTPConfirmation.setText("");
                }
            }
        });

        ((CardLayout)container1.getLayout()).show(container1, "OTPCustomer");


    }//GEN-LAST:event_confirm1ActionPerformed
//FOREIGN EXCHANGE
    private void confirm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm2ActionPerformed
        while (true) {
        String nameFE = name2.getText().trim();
        String chang = (String) change.getSelectedItem();
        String am = amount3.getText().trim();
        String conver = (String) convert.getSelectedItem();

        if (nameFE.isEmpty() && chang.isEmpty() && am.isEmpty() && conver.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
        } else if (nameFE.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input your Name", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
//        Validation Name
          else if (nameFE.length() > 50) {
            JOptionPane.showMessageDialog(null, "Name must be 50 characters or fewer", "Name Error", JOptionPane.ERROR_MESSAGE);
            name2.setText(""); // Optional: clear the field
            return;
        }
//          ✅ Validate name contains only letters and spaces
          else if (!nameFE.matches("[a-zA-Z\\s]+")) {
            JOptionPane.showMessageDialog(null, "Name must contain letters only (no numbers or symbols)", "Name Error", JOptionPane.ERROR_MESSAGE);
            name2.setText(""); // Optional: clear the field
            return;
        }
        else if (chang.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select Currency to Change", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (am.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input amount", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
//        Validation amount
        else if (!am.matches("\\d{1,6}")) {
            JOptionPane.showMessageDialog(null, "Amount must be less than 6 digits and contain numbers only", "Amount Error", JOptionPane.ERROR_MESSAGE);
            amount3.setText(""); // Optional: clear the field
            return;
        }
        else if (conver.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select Conversion", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            int c = JOptionPane.showConfirmDialog(null,"Are you sure the information is correct?","Confirmation",JOptionPane.OK_CANCEL_OPTION      );
            
            if (c == JOptionPane.OK_OPTION) {
                
                Integer servedNum = QUEUEING.queueC.peek(); 
                if (servedNum != null) {
                    int index = servedNum - 1;
                    if (index >= 0 && index < QUEUEING.nameFE.size()) {
                        QUEUEING.nameFE.add(index, nameFE);
                        QUEUEING.changeFE.add(index, chang);
                        QUEUEING.amountFE.add(index, am);
                        QUEUEING.convertFE.add(index, conver);
                        
                        
                        double amount = Double.parseDouble(am);
                        double convertedAmount = 0.0;
                        switch (chang.toUpperCase()) {
                            case "USD":
                                convertedAmount = amount * 56.5;
                                break;
                            case "EUR":
                                convertedAmount = amount * 60.2;
                                break;
                            case "JPY":
                                convertedAmount = amount * 0.38;
                                break;
                            default:
                                convertedAmount = amount;
                        }

                        String formattedCon = String.format("%.2f", convertedAmount);

                        if (index < QUEUEING.conAmountFE.size()) {
                            QUEUEING.conAmountFE.set(index, formattedCon);
                        } else {
                        }

                    }
                }

                JOptionPane.showMessageDialog(null,
                        "Information has been updated and saved.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                
                TICKET ticketFrame = new TICKET();
                ticketFrame.setVisible(true);
                QUEUEING.printReceiptC();
                
                name2.setEnabled(false);
                change.setEnabled(false);
                amount3.setEnabled(false);
                convert.setEnabled(false);
                conAmount.setEnabled(false);
                
//NEXTCUSTOMER               
            servedNum = QUEUEING.queueC.poll();
            if (servedNum != null) {
                int index = servedNum - 1; 
               QUEUEING.showCurrentC();
               QUEUEING.servedCountC++;;
              noOfServedC.setText(String.valueOf(QUEUEING.servedCountC));
            } else {
                serveC.setText(null);
                TV.serveC.setText(null);
                name2.setText("");
                convert.setSelectedItem("");
                amount3.setText("");
                conAmount.setText("");
            }
                 new javax.swing.Timer(5000, e -> {
               
                    ticketFrame.dispose();
             }).start();
            } 
            break;
        }
        }
    }//GEN-LAST:event_confirm2ActionPerformed

    private void call1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_call1ActionPerformed
       QUEUEING.playClickSound();
    }//GEN-LAST:event_call1ActionPerformed

    private void call2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_call2ActionPerformed
        QUEUEING.playClickSound();
    }//GEN-LAST:event_call2ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed

       int option = JOptionPane.showConfirmDialog(null,"Are you sure you want to logout?","Logout?",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        
         if (option == JOptionPane.OK_OPTION) {
  
        for (java.awt.Window w : java.awt.Window.getWindows()) {
             w.setVisible(false);
        }

        new EMPLOYEE().setVisible(true);
    }
    }//GEN-LAST:event_logoutActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        name.setEnabled(true);
        pay.setEnabled(true);
        amount.setEnabled(true);
    }//GEN-LAST:event_editActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed

        while (true) {
            String enteredName = name.getText().trim();
            String enteredPay = (String) pay.getSelectedItem();
            String enteredAmount = amount.getText().trim();
            String enteredReceived = AmountReceived.getText().trim();

            if (enteredName.isEmpty() && enteredPay.isEmpty() && enteredAmount.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill in all fields", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (enteredName.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please input your Name", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // Validation Name
            else if (enteredName.length() > 50) {
                JOptionPane.showMessageDialog(null, "Name must be 50 characters or fewer", "Name Error", JOptionPane.ERROR_MESSAGE);
                name.setText("");
                return;
            }
            // ✅ Validate name contains only letters and spaces
            else if (!enteredName.matches("[a-zA-Z\\s]+")) {
                JOptionPane.showMessageDialog(null, "Name must contain letters only (no numbers or symbols)", "Name Error", JOptionPane.ERROR_MESSAGE);
                name.setText("");
                return;
            }
            else if (enteredPay.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill in Pay To field", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (enteredAmount.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please input an Amount", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // Validation amount
            else if (!enteredAmount.matches("\\d{1,6}")) {
                JOptionPane.showMessageDialog(null, "Amount must be less than 6 digits and contain numbers only", "Amount Error", JOptionPane.ERROR_MESSAGE);
                amount.setText("");
                return;
            } else if (enteredReceived.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please input the Amount Received", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // Validate amount received is numeric
            else if (!enteredReceived.matches("\\d+(\\.\\d{1,2})?")) {
                JOptionPane.showMessageDialog(null, "Amount Received must be a valid number", "Amount Error", JOptionPane.ERROR_MESSAGE);
                AmountReceived.setText("");
                return;
            }
            // Check if amount received >= amount
            else {
                double amountValue = Double.parseDouble(enteredAmount);
                double receivedValue = Double.parseDouble(enteredReceived);

                if (receivedValue < amountValue) {
                    JOptionPane.showMessageDialog(null, "Amount Received must be greater than or equal to the Amount", "Amount Error", JOptionPane.ERROR_MESSAGE);
                    AmountReceived.setText("");
                    return;
                }

                int c = JOptionPane.showConfirmDialog(null,"Are you sure the information is correct?","Confirmation",JOptionPane.OK_CANCEL_OPTION);

                if (c == JOptionPane.OK_OPTION) {
                    Integer servedNum = QUEUEING.queueA.peek();
                    if (servedNum != null) {
                        int index = servedNum - 1;

                        if (index >= 0 && index < QUEUEING.nameBP.size()) {
                            QUEUEING.receivedBP.add(enteredReceived);
                            QUEUEING.nameBP.add(index, enteredName);
                            QUEUEING.payToBP.add(index, enteredPay);
                            QUEUEING.amountBP.add(index, enteredAmount);
                            QUEUEING.receivedBP.add(index, enteredReceived);
                        }
                    }

                    JOptionPane.showMessageDialog(null,
                        "Information has been updated and saved.",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                    TICKET ticketFrame = new TICKET();
                    ticketFrame.setVisible(true);
                    QUEUEING.printReceiptA();

                    servedNum = QUEUEING.queueA.poll();
                    if (servedNum != null) {
                        int index = servedNum - 1;
                        QUEUEING.servedCountA++;
                        noOfServedA.setText(String.valueOf(QUEUEING.servedCountA));
                        QUEUEING.showCurrentA();
                        System.out.println(queueA);
                    } else {
                        serveA.setText(null);
                        TV.serveA.setText(null);
                        name.setText("");
                        pay.setSelectedItem(null);
                        amount.setText("");
                        AmountReceived.setText("");
                    }

                    name.setEnabled(false);
                    pay.setEnabled(false);
                    amount.setEnabled(false);

                    new javax.swing.Timer(5000, e -> {
                        ticketFrame.dispose();
                    }).start();
                }
                break;
            }
        }


        
    }//GEN-LAST:event_confirmActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        //BILLS PAYMENT
        if (QUEUEING.queueA.isEmpty()) {
            JOptionPane.showMessageDialog(null, "The queue is empty!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Integer servedNum = QUEUEING.queueA.poll();
            if (servedNum != null) {
                QUEUEING.showCurrentA();
            } else {
                serveA.setText(null);
                TV.serveA.setText(null);
                name.setText("");
                pay.setSelectedItem(null);
                amount.setText("");
            }
        }
    }//GEN-LAST:event_cancelActionPerformed

    private void callActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callActionPerformed
        QUEUEING.playClickSound();

    }//GEN-LAST:event_callActionPerformed

    private void exchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exchangeActionPerformed
        ((CardLayout)container1.getLayout()).show(container1, "EDASH");
    }//GEN-LAST:event_exchangeActionPerformed

    private void applicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicationActionPerformed
        ((CardLayout)container1.getLayout()).show(container1, "ADASH");

    }//GEN-LAST:event_applicationActionPerformed

    private void conAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conAmountActionPerformed

    private void holdBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holdBActionPerformed
        QUEUEING.holdCurrentB();
        QUEUEING.showCurrentB();
    }//GEN-LAST:event_holdBActionPerformed

    private void recallBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recallBActionPerformed
        QUEUEING.recallHeldB();
        QUEUEING.showCurrentB();
    }//GEN-LAST:event_recallBActionPerformed

    private void holdCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holdCActionPerformed
        QUEUEING.holdCurrentC();
        QUEUEING.showCurrentC();
    }//GEN-LAST:event_holdCActionPerformed

    private void recallCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recallCActionPerformed
        QUEUEING.recallHeldA();
        QUEUEING.showCurrentA();
    }//GEN-LAST:event_recallCActionPerformed

    private void holdAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holdAActionPerformed
        QUEUEING.holdCurrentA();
        QUEUEING.showCurrentA();
    }//GEN-LAST:event_holdAActionPerformed

    private void recallAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recallAActionPerformed
        QUEUEING.recallHeldA();
        QUEUEING.showCurrentA();
    }//GEN-LAST:event_recallAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DASHBOARD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Abg;
    private javax.swing.JLabel Abg1;
    public static javax.swing.JTextField AmountReceived;
    private javax.swing.JLabel Bbg;
    public static javax.swing.JTextField address1;
    public static javax.swing.JTextField amount;
    public static javax.swing.JTextField amount3;
    private javax.swing.JButton application;
    private javax.swing.JButton application2;
    private javax.swing.JPanel applidash;
    public static com.toedter.calendar.JDateChooser bday;
    private javax.swing.JPanel billsdash;
    private javax.swing.JButton billspayment;
    private javax.swing.JButton billspayment1;
    private javax.swing.JButton call;
    private javax.swing.JButton call1;
    private javax.swing.JButton call2;
    private javax.swing.JButton cancel;
    private javax.swing.JButton cancel1;
    private javax.swing.JButton cancel2;
    public static javax.swing.JComboBox<String> change;
    public static javax.swing.JTextField conAmount;
    private javax.swing.JButton confirm;
    private javax.swing.JButton confirm1;
    private javax.swing.JButton confirm2;
    private javax.swing.JPanel container1;
    public static javax.swing.JComboBox<String> convert;
    private javax.swing.JButton edit;
    private javax.swing.JButton edit1;
    private javax.swing.JButton edit2;
    public static javax.swing.JTextField email;
    private javax.swing.JButton exchange;
    private javax.swing.JButton exchange1;
    private javax.swing.JPanel exchangedash;
    public static javax.swing.JButton holdA;
    public static javax.swing.JButton holdB;
    public static javax.swing.JButton holdC;
    public static javax.swing.JTextArea holdListA;
    public static javax.swing.JTextArea holdListB;
    public static javax.swing.JTextArea holdListC;
    public static javax.swing.JLabel inQueueA;
    public static javax.swing.JLabel inQueueB;
    public static javax.swing.JLabel inQueueC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logout;
    private javax.swing.JButton logout1;
    private javax.swing.JButton logout2;
    public static javax.swing.JTextField name;
    public static javax.swing.JTextField name1;
    public static javax.swing.JTextField name2;
    public static javax.swing.JLabel noOfServedA;
    public static javax.swing.JLabel noOfServedB;
    public static javax.swing.JLabel noOfServedC;
    public static javax.swing.JTextField number;
    public static javax.swing.JTextField occupation;
    public static javax.swing.JComboBox<String> pay;
    public static javax.swing.JButton recallA;
    public static javax.swing.JButton recallB;
    public static javax.swing.JButton recallC;
    public static javax.swing.JLabel serveA;
    public static javax.swing.JLabel serveB;
    public static javax.swing.JLabel serveC;
    // End of variables declaration//GEN-END:variables
}
