/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.queueing;

import static com.mycompany.queueing.QUEUEING.queueA;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author lucky
 */
public class DASHBOARD extends javax.swing.JFrame {

   

    /**
     * Creates new form DASHBOARD
     */
    public DASHBOARD() {
        initComponents();
        convert.setOpaque(false); 
        convert.setBackground(new Color(0, 0, 0, 0)); 
        
   
            
            
   }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container1 = new javax.swing.JPanel();
        billsdash = new javax.swing.JPanel();
        application = new javax.swing.JButton();
        exchange = new javax.swing.JButton();
        call = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        next = new javax.swing.JButton();
        amount = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        pay = new javax.swing.JComboBox<>();
        serveA = new javax.swing.JLabel();
        noOfServedA = new javax.swing.JLabel();
        Bbg = new javax.swing.JLabel();
        applidash = new javax.swing.JPanel();
        billspayment = new javax.swing.JButton();
        exchange1 = new javax.swing.JButton();
        call1 = new javax.swing.JButton();
        cancel1 = new javax.swing.JButton();
        next1 = new javax.swing.JButton();
        number = new javax.swing.JTextField();
        bday = new javax.swing.JTextField();
        name1 = new javax.swing.JTextField();
        confirm1 = new javax.swing.JButton();
        edit1 = new javax.swing.JButton();
        logout1 = new javax.swing.JButton();
        address1 = new javax.swing.JTextField();
        occupation = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        serveB = new javax.swing.JLabel();
        noOfServedB = new javax.swing.JLabel();
        Abg = new javax.swing.JLabel();
        exchangedash = new javax.swing.JPanel();
        billspayment1 = new javax.swing.JButton();
        application2 = new javax.swing.JButton();
        call2 = new javax.swing.JButton();
        cancel2 = new javax.swing.JButton();
        next2 = new javax.swing.JButton();
        change = new javax.swing.JTextField();
        amount3 = new javax.swing.JTextField();
        name2 = new javax.swing.JTextField();
        confirm2 = new javax.swing.JButton();
        edit2 = new javax.swing.JButton();
        logout2 = new javax.swing.JButton();
        convert = new javax.swing.JComboBox<>();
        serveC = new javax.swing.JLabel();
        noOfServedC = new javax.swing.JLabel();
        Abg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 50));
        setMinimumSize(new java.awt.Dimension(891, 546));
        setUndecorated(true);
        getContentPane().setLayout(null);

        container1.setLayout(new java.awt.CardLayout());

        billsdash.setLayout(null);

        application.setBorderPainted(false);
        application.setContentAreaFilled(false);
        application.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicationActionPerformed(evt);
            }
        });
        billsdash.add(application);
        application.setBounds(10, 227, 140, 30);

        exchange.setBorderPainted(false);
        exchange.setContentAreaFilled(false);
        exchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exchangeActionPerformed(evt);
            }
        });
        billsdash.add(exchange);
        exchange.setBounds(10, 320, 140, 30);

        call.setBorderPainted(false);
        call.setContentAreaFilled(false);
        call.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callActionPerformed(evt);
            }
        });
        billsdash.add(call);
        call.setBounds(410, 90, 140, 40);

        cancel.setBorderPainted(false);
        cancel.setContentAreaFilled(false);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        billsdash.add(cancel);
        cancel.setBounds(410, 150, 140, 40);

        next.setBorderPainted(false);
        next.setContentAreaFilled(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        billsdash.add(next);
        next.setBounds(410, 30, 140, 50);

        amount.setBackground(new java.awt.Color(255, 255, 255));
        amount.setForeground(new java.awt.Color(0, 0, 0));
        amount.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        amount.setEnabled(false);
        billsdash.add(amount);
        amount.setBounds(280, 430, 320, 20);

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setForeground(new java.awt.Color(0, 0, 0));
        name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        name.setCaretColor(new java.awt.Color(255, 255, 255));
        name.setEnabled(false);
        billsdash.add(name);
        name.setBounds(270, 330, 330, 20);

        confirm.setBorderPainted(false);
        confirm.setContentAreaFilled(false);
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        billsdash.add(confirm);
        confirm.setBounds(410, 500, 90, 20);

        edit.setBorderPainted(false);
        edit.setContentAreaFilled(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        billsdash.add(edit);
        edit.setBounds(300, 497, 90, 30);

        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        billsdash.add(logout);
        logout.setBounds(30, 510, 100, 20);

        pay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        billsdash.add(pay);
        pay.setBounds(280, 370, 310, 40);

        serveA.setFont(new java.awt.Font("Arial Black", 1, 54)); // NOI18N
        serveA.setForeground(new java.awt.Color(153, 0, 0));
        serveA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billsdash.add(serveA);
        serveA.setBounds(220, 70, 140, 120);

        noOfServedA.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        noOfServedA.setForeground(new java.awt.Color(153, 51, 0));
        noOfServedA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        billsdash.add(noOfServedA);
        noOfServedA.setBounds(820, 30, 40, 50);

        Bbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bills payment dashboard.png"))); // NOI18N
        billsdash.add(Bbg);
        Bbg.setBounds(-5, 0, 900, 550);

        container1.add(billsdash, "BDASH");

        applidash.setLayout(null);

        billspayment.setBorderPainted(false);
        billspayment.setContentAreaFilled(false);
        billspayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billspaymentActionPerformed(evt);
            }
        });
        applidash.add(billspayment);
        billspayment.setBounds(10, 130, 140, 30);

        exchange1.setBorderPainted(false);
        exchange1.setContentAreaFilled(false);
        exchange1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exchange1ActionPerformed(evt);
            }
        });
        applidash.add(exchange1);
        exchange1.setBounds(10, 320, 140, 30);

        call1.setBorderPainted(false);
        call1.setContentAreaFilled(false);
        applidash.add(call1);
        call1.setBounds(410, 90, 140, 40);

        cancel1.setBorderPainted(false);
        cancel1.setContentAreaFilled(false);
        cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel1ActionPerformed(evt);
            }
        });
        applidash.add(cancel1);
        cancel1.setBounds(410, 150, 140, 40);

        next1.setBorderPainted(false);
        next1.setContentAreaFilled(false);
        next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1ActionPerformed(evt);
            }
        });
        applidash.add(next1);
        next1.setBounds(410, 30, 140, 50);

        number.setBackground(new java.awt.Color(255, 255, 255));
        number.setBorder(null);
        number.setEnabled(false);
        applidash.add(number);
        number.setBounds(270, 370, 250, 20);

        bday.setBackground(new java.awt.Color(255, 255, 255));
        bday.setBorder(null);
        bday.setEnabled(false);
        bday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdayActionPerformed(evt);
            }
        });
        applidash.add(bday);
        bday.setBounds(270, 470, 250, 20);

        name1.setBackground(new java.awt.Color(255, 255, 255));
        name1.setBorder(null);
        name1.setEnabled(false);
        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        applidash.add(name1);
        name1.setBounds(270, 320, 250, 20);

        confirm1.setBorderPainted(false);
        confirm1.setContentAreaFilled(false);
        confirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm1ActionPerformed(evt);
            }
        });
        applidash.add(confirm1);
        confirm1.setBounds(700, 420, 100, 20);

        edit1.setBorderPainted(false);
        edit1.setContentAreaFilled(false);
        edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit1ActionPerformed(evt);
            }
        });
        applidash.add(edit1);
        edit1.setBounds(600, 420, 90, 20);

        logout1.setBorderPainted(false);
        logout1.setContentAreaFilled(false);
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });
        applidash.add(logout1);
        logout1.setBounds(30, 510, 100, 20);

        address1.setBackground(new java.awt.Color(255, 255, 255));
        address1.setBorder(null);
        address1.setEnabled(false);
        address1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address1ActionPerformed(evt);
            }
        });
        applidash.add(address1);
        address1.setBounds(270, 420, 250, 20);

        occupation.setBackground(new java.awt.Color(255, 255, 255));
        occupation.setEnabled(false);
        applidash.add(occupation);
        occupation.setBounds(620, 320, 230, 22);

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setEnabled(false);
        applidash.add(email);
        email.setBounds(630, 370, 220, 22);

        serveB.setFont(new java.awt.Font("Arial Black", 1, 54)); // NOI18N
        serveB.setForeground(new java.awt.Color(153, 0, 0));
        serveB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        applidash.add(serveB);
        serveB.setBounds(220, 70, 140, 120);

        noOfServedB.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        noOfServedB.setForeground(new java.awt.Color(153, 51, 0));
        noOfServedB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        applidash.add(noOfServedB);
        noOfServedB.setBounds(820, 30, 40, 50);

        Abg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application dashboard.png"))); // NOI18N
        applidash.add(Abg);
        Abg.setBounds(-5, 0, 900, 550);

        container1.add(applidash, "ADASH");

        exchangedash.setLayout(null);

        billspayment1.setBorderPainted(false);
        billspayment1.setContentAreaFilled(false);
        billspayment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billspayment1ActionPerformed(evt);
            }
        });
        exchangedash.add(billspayment1);
        billspayment1.setBounds(10, 130, 140, 30);

        application2.setBorderPainted(false);
        application2.setContentAreaFilled(false);
        application2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                application2ActionPerformed(evt);
            }
        });
        exchangedash.add(application2);
        application2.setBounds(10, 230, 140, 30);

        call2.setBorderPainted(false);
        call2.setContentAreaFilled(false);
        exchangedash.add(call2);
        call2.setBounds(410, 90, 140, 40);

        cancel2.setBorderPainted(false);
        cancel2.setContentAreaFilled(false);
        cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel2ActionPerformed(evt);
            }
        });
        exchangedash.add(cancel2);
        cancel2.setBounds(410, 150, 140, 40);

        next2.setBorderPainted(false);
        next2.setContentAreaFilled(false);
        next2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next2ActionPerformed(evt);
            }
        });
        exchangedash.add(next2);
        next2.setBounds(410, 30, 140, 50);

        change.setBackground(new java.awt.Color(255, 255, 255));
        change.setBorder(null);
        change.setEnabled(false);
        exchangedash.add(change);
        change.setBounds(320, 370, 240, 20);

        amount3.setBackground(new java.awt.Color(255, 255, 255));
        amount3.setBorder(null);
        amount3.setEnabled(false);
        amount3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount3ActionPerformed(evt);
            }
        });
        exchangedash.add(amount3);
        amount3.setBounds(270, 470, 290, 20);

        name2.setBackground(new java.awt.Color(255, 255, 255));
        name2.setBorder(null);
        name2.setEnabled(false);
        exchangedash.add(name2);
        name2.setBounds(270, 320, 290, 20);

        confirm2.setBorderPainted(false);
        confirm2.setContentAreaFilled(false);
        confirm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm2ActionPerformed(evt);
            }
        });
        exchangedash.add(confirm2);
        confirm2.setBounds(390, 500, 90, 30);

        edit2.setBorderPainted(false);
        edit2.setContentAreaFilled(false);
        edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit2ActionPerformed(evt);
            }
        });
        exchangedash.add(edit2);
        edit2.setBounds(280, 500, 100, 30);

        logout2.setBorderPainted(false);
        logout2.setContentAreaFilled(false);
        logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout2ActionPerformed(evt);
            }
        });
        exchangedash.add(logout2);
        logout2.setBounds(30, 510, 100, 20);

        convert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MAYNILAD", "MERALCO", "GLOBE", "PLDT", "SMART" }));
        convert.setEnabled(false);
        exchangedash.add(convert);
        convert.setBounds(270, 416, 290, 30);

        serveC.setFont(new java.awt.Font("Arial Black", 1, 54)); // NOI18N
        serveC.setForeground(new java.awt.Color(153, 0, 0));
        serveC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exchangedash.add(serveC);
        serveC.setBounds(220, 70, 140, 120);

        noOfServedC.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        noOfServedC.setForeground(new java.awt.Color(153, 51, 0));
        noOfServedC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exchangedash.add(noOfServedC);
        noOfServedC.setBounds(820, 30, 40, 50);

        Abg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foreign ex dashboard.png"))); // NOI18N
        exchangedash.add(Abg1);
        Abg1.setBounds(-5, 0, 900, 550);

        container1.add(exchangedash, "EDASH");

        getContentPane().add(container1);
        container1.setBounds(0, 0, 893, 548);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdayActionPerformed

    private void address1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address1ActionPerformed

    private void amount3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount3ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        
        
        int option = JOptionPane.showConfirmDialog(null,"Are you sure you want to logout?","Logout?",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        
        if (option == JOptionPane.OK_OPTION) {
            this.setVisible(false);
            new EMPLOYEE().setVisible(true);
            new TV().setVisible(false);
            new CUSTOMER().setVisible(false);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void applicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicationActionPerformed
        ((CardLayout)container1.getLayout()).show(container1, "ADASH");
        
    }//GEN-LAST:event_applicationActionPerformed

    private void exchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exchangeActionPerformed
        ((CardLayout)container1.getLayout()).show(container1, "EDASH");
    }//GEN-LAST:event_exchangeActionPerformed

    private void billspaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billspaymentActionPerformed
        ((CardLayout)container1.getLayout()).show(container1, "BDASH");
    }//GEN-LAST:event_billspaymentActionPerformed

    private void exchange1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exchange1ActionPerformed
        ((CardLayout)container1.getLayout()).show(container1, "EDASH");
    }//GEN-LAST:event_exchange1ActionPerformed

    private void application2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_application2ActionPerformed
        ((CardLayout)container1.getLayout()).show(container1, "ADASH");
    }//GEN-LAST:event_application2ActionPerformed

    private void billspayment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billspayment1ActionPerformed
        ((CardLayout)container1.getLayout()).show(container1, "EDASH");
    }//GEN-LAST:event_billspayment1ActionPerformed

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
        
        int option = JOptionPane.showConfirmDialog(null,"Are you sure you want to logout?","Logout?",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        
        if (option == JOptionPane.OK_OPTION) {
            this.setVisible(false);
            new EMPLOYEE().setVisible(true);
            new TV().setVisible(false);
            new CUSTOMER().setVisible(false);
        }
    }//GEN-LAST:event_logout1ActionPerformed

    private void logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout2ActionPerformed
        
        int option = JOptionPane.showConfirmDialog(null,"Are you sure you want to logout?","Logout?",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        
        if (option == JOptionPane.OK_OPTION) {
            this.setVisible(false);
            new EMPLOYEE().setVisible(true);
            new TV().setVisible(false);
            new CUSTOMER().setVisible(false);
        }
    }//GEN-LAST:event_logout2ActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        name.setEnabled(true);
        pay.setEnabled(true);
        amount.setEnabled(true);
    }//GEN-LAST:event_editActionPerformed

    private void edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit1ActionPerformed
        name1.setEnabled(true);
        number.setEnabled(true);
        address1.setEnabled(true);
        bday.setEnabled(true);
        occupation.setEnabled(true);
        email.setEnabled(true);
    }//GEN-LAST:event_edit1ActionPerformed

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void edit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit2ActionPerformed
        name2.setEnabled(true);
        change.setEnabled(true);
        amount.setEnabled(true);
        convert.setEnabled(true);
    }//GEN-LAST:event_edit2ActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        
        while (true) {
        String enteredName = name.getText().trim();
        String enteredPay = (String) pay.getSelectedItem();
        String enteredAmount = amount.getText().trim();

        if (enteredName.isEmpty() && enteredPay.isEmpty() && enteredAmount.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
        } else if (enteredName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input your Name", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (enteredPay.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in Pay To field", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (enteredAmount.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input an Amount", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            int c = JOptionPane.showConfirmDialog(null,"Are you sure the information is correct?","Confirmation",JOptionPane.OK_CANCEL_OPTION      );
            
            if (c == JOptionPane.OK_OPTION) {
                JOptionPane.showMessageDialog(null,"Your information has been saved.","Success",JOptionPane.INFORMATION_MESSAGE);
                name2.setEnabled(false);
                change.setEnabled(false);
                amount.setEnabled(false);
                convert.setEnabled(false);
            } 
            break;
        }
    }
        
    }//GEN-LAST:event_confirmActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
       //BILLS PAYMENT
      
        Integer servedNum = QUEUEING.queueA.poll(); 
            if (servedNum != null) {
                int index = servedNum - 1; 
                QUEUEING.servedCountA++;;
                noOfServedA.setText(String.valueOf(QUEUEING.servedCountA));
                QUEUEING.showCurrentA();
                System.out.println(queueA);
            } else {
                serveA.setText(null);
                TV.serveA.setText(null);
                name.setText("");
                pay.setSelectedItem(null);
                amount.setText("");
    }

    }//GEN-LAST:event_nextActionPerformed

    private void callActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callActionPerformed
        
      
    }//GEN-LAST:event_callActionPerformed

    private void next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1ActionPerformed
      //APPLICATION
        Integer servedNum = QUEUEING.queueB.poll();
          if (servedNum != null) {
              int index = servedNum - 1; 
              
              QUEUEING.showCurrentB();
              QUEUEING.servedCountB++;;
              noOfServedB.setText(String.valueOf(QUEUEING.servedCountB));
          } else {
              serveB.setText(null);
              TV.serveB.setText(null);
              name1.setText("");
              number.setText("");
              address1.setText("");
              bday.setText("");
              occupation.setText("");
              email.setText("");
          }
    }//GEN-LAST:event_next1ActionPerformed

    private void next2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next2ActionPerformed
        //FOREIGN EXCHANGE
        Integer servedNum = QUEUEING.queueC.poll();
            if (servedNum != null) {
                int index = servedNum - 1; 
               QUEUEING.showCurrentC();
               QUEUEING.servedCountC++;;
              noOfServedC.setText(String.valueOf(QUEUEING.servedCountC));
            } else {
                serveC.setText(null);
                TV.serveC.setText(null);
                name2.setText("");
                change.setText("");
                convert.setSelectedItem("");
                amount3.setText("");
            }
    }//GEN-LAST:event_next2ActionPerformed

    private void cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel1ActionPerformed
         //APPLICATION
        Integer servedNum = QUEUEING.queueB.poll();
          if (servedNum != null) {
              int index = servedNum - 1; 
              QUEUEING.showCurrentB();
          } else {
              serveB.setText(null);
              TV.serveB.setText(null);
              name1.setText("");
              number.setText("");
              address1.setText("");
              bday.setText("");
              occupation.setText("");
              email.setText("");
          }
    }//GEN-LAST:event_cancel1ActionPerformed

    private void cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel2ActionPerformed
       //FOREIGN EXCHANGE
        Integer servedNum = QUEUEING.queueC.poll();
            if (servedNum != null) {
                int index = servedNum - 1; 
               QUEUEING.showCurrentC();
            } else {
                serveC.setText(null);
                TV.serveC.setText(null);
                name2.setText("");
                change.setText("");
                convert.setSelectedItem("");
                amount3.setText("");
            }
    }//GEN-LAST:event_cancel2ActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        //BILLS PAYMENT
        Integer servedNum = QUEUEING.queueA.poll(); 
            if (servedNum != null) {
                QUEUEING.showCurrentA();
            } else {
                serveA.setText(null);
                TV.serveA.setText(null);
                name.setText("");
                pay.setSelectedItem(null);
                amount.setText("");
    }
    }//GEN-LAST:event_cancelActionPerformed

    private void confirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm1ActionPerformed
        
        while (true) {
        String fullname = name1.getText().trim();
        String num = number.getText().trim();
        String bda = bday.getText().trim();
        String add = address1.getText().trim();
        String occu = occupation.getText().trim();
        String ema = email.getText().trim();

        if (fullname.isEmpty() && num.isEmpty() && bda.isEmpty() && add.isEmpty() && occu.isEmpty() && ema.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
        } else if (fullname.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input your Name", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (num.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input your Number", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (add.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input your Address", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (bda.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input your Birthday", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (occu.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input your Occupation", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (ema.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input your Email Address", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            int c = JOptionPane.showConfirmDialog(null,"Are you sure the information is correct?","Confirmation",JOptionPane.OK_CANCEL_OPTION      );
            
            if (c == JOptionPane.OK_OPTION) {
                JOptionPane.showMessageDialog(null,"Your information has been saved.","Success",JOptionPane.INFORMATION_MESSAGE);
                name1.setEnabled(false);
                number.setEnabled(false);
                address1.setEnabled(false);
                bday.setEnabled(false);
                occupation.setEnabled(false);
                email.setEnabled(false);
            } 
            break;
        }
    }
    }//GEN-LAST:event_confirm1ActionPerformed

    private void confirm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm2ActionPerformed
        while (true) {
        String nameFE = name2.getText().trim();
        String chang = change.getText().trim();
        String am = amount3.getText().trim();
        String conver = (String) convert.getSelectedItem();

        if (nameFE.isEmpty() && chang.isEmpty() && am.isEmpty() && conver.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill in all fields", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; 
        } else if (nameFE.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input your Name", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (chang.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select Currency to Change", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (am.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please input amount", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (conver.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please select Conversion", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            int c = JOptionPane.showConfirmDialog(null,"Are you sure the information is correct?","Confirmation",JOptionPane.OK_CANCEL_OPTION      );
            
            if (c == JOptionPane.OK_OPTION) {
                JOptionPane.showMessageDialog(null,"Your information has been saved.","Success",JOptionPane.INFORMATION_MESSAGE);
                name2.setEnabled(false);
                change.setEnabled(false);
                amount3.setEnabled(false);
                convert.setEnabled(false);
            } 
            break;
        }
        }
    }//GEN-LAST:event_confirm2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DASHBOARD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Abg;
    private javax.swing.JLabel Abg1;
    private javax.swing.JLabel Bbg;
    public static javax.swing.JTextField address1;
    public static javax.swing.JTextField amount;
    public static javax.swing.JTextField amount3;
    private javax.swing.JButton application;
    private javax.swing.JButton application2;
    private javax.swing.JPanel applidash;
    public static javax.swing.JTextField bday;
    private javax.swing.JPanel billsdash;
    private javax.swing.JButton billspayment;
    private javax.swing.JButton billspayment1;
    private javax.swing.JButton call;
    private javax.swing.JButton call1;
    private javax.swing.JButton call2;
    private javax.swing.JButton cancel;
    private javax.swing.JButton cancel1;
    private javax.swing.JButton cancel2;
    public static javax.swing.JTextField change;
    private javax.swing.JButton confirm;
    private javax.swing.JButton confirm1;
    private javax.swing.JButton confirm2;
    private javax.swing.JPanel container1;
    public static javax.swing.JComboBox<String> convert;
    private javax.swing.JButton edit;
    private javax.swing.JButton edit1;
    private javax.swing.JButton edit2;
    public static javax.swing.JTextField email;
    private javax.swing.JButton exchange;
    private javax.swing.JButton exchange1;
    private javax.swing.JPanel exchangedash;
    private javax.swing.JButton logout;
    private javax.swing.JButton logout1;
    private javax.swing.JButton logout2;
    public static javax.swing.JTextField name;
    public static javax.swing.JTextField name1;
    public static javax.swing.JTextField name2;
    private javax.swing.JButton next;
    private javax.swing.JButton next1;
    private javax.swing.JButton next2;
    public static javax.swing.JLabel noOfServedA;
    public static javax.swing.JLabel noOfServedB;
    public static javax.swing.JLabel noOfServedC;
    public static javax.swing.JTextField number;
    public static javax.swing.JTextField occupation;
    public static javax.swing.JComboBox<String> pay;
    public static javax.swing.JLabel serveA;
    public static javax.swing.JLabel serveB;
    public static javax.swing.JLabel serveC;
    // End of variables declaration//GEN-END:variables
}
