/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.queueing;

/**
 *
 * @author lucky
 */
public class OTPCustomer extends javax.swing.JFrame {
    
    /**
     * Creates new form OTP
     */
    public OTPCustomer() {
        initComponents();
        this.setLocation(1000, 100);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        OTPText = new javax.swing.JLabel();
        OTPBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(300, 400));
        setMinimumSize(new java.awt.Dimension(400, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        OTPText.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 36)); // NOI18N
        OTPText.setForeground(new java.awt.Color(153, 102, 0));
        OTPText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(OTPText);
        OTPText.setBounds(60, 430, 270, 50);

        OTPBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final Design/otpcus.png"))); // NOI18N
        jPanel1.add(OTPBG);
        OTPBG.setBounds(0, 0, 400, 600);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OTPCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OTPCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OTPCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OTPCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OTPCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OTPBG;
    public static javax.swing.JLabel OTPText;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
