/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.queueing;

import java.awt.Color;

/**
 *
 * @author lucky
 */
public class OTPEmployee extends javax.swing.JFrame {

    /**
     * Creates new form OTPEmployee
     */
    public OTPEmployee() {
        initComponents();
        this.setLocation(580, 300);
        OTPConfirmation.setBackground(new Color(0, 0, 0, 0)); 
        enter.setBackground(new Color(0, 0, 0, 0)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        OTPConfirmation = new javax.swing.JTextField();
        enter = new javax.swing.JButton();
        OTPEBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 300, 400, 200));
        setMinimumSize(new java.awt.Dimension(400, 200));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        OTPConfirmation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OTPConfirmation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        OTPConfirmation.setBorder(null);
        jPanel1.add(OTPConfirmation);
        OTPConfirmation.setBounds(125, 110, 150, 20);

        enter.setBorder(null);
        enter.setContentAreaFilled(false);
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        jPanel1.add(enter);
        enter.setBounds(150, 150, 100, 30);

        OTPEBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Final Design/otp verification .png"))); // NOI18N
        jPanel1.add(OTPEBG);
        OTPEBG.setBounds(0, 0, 400, 200);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OTPEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OTPEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OTPEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OTPEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OTPEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField OTPConfirmation;
    private javax.swing.JLabel OTPEBG;
    public static javax.swing.JButton enter;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
