/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.queueing;

import java.awt.Color;

/**
 *
 * @author lucky
 */
public class TV extends javax.swing.JFrame {

    
    
    /**
     * Creates new form TV
     */
    public TV() {
        initComponents();
         waitingA.setBackground(new Color(0, 0, 0, 0)); 
         waitingB.setBackground(new Color(0, 0, 0, 0)); 
         waitingC.setBackground(new Color(0, 0, 0, 0)); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        serveB = new javax.swing.JLabel();
        serveC = new javax.swing.JLabel();
        serveA = new javax.swing.JLabel();
        waitingB = new javax.swing.JTextField();
        waitingC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        waitingA = new javax.swing.JTextArea();
        TVbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(755, 383));
        setMinimumSize(new java.awt.Dimension(790, 400));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        serveB.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        serveB.setForeground(new java.awt.Color(153, 0, 0));
        serveB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(serveB);
        serveB.setBounds(320, 130, 150, 80);

        serveC.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        serveC.setForeground(new java.awt.Color(153, 0, 0));
        serveC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(serveC);
        serveC.setBounds(560, 130, 150, 80);

        serveA.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        serveA.setForeground(new java.awt.Color(153, 0, 0));
        serveA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(serveA);
        serveA.setBounds(90, 140, 150, 80);

        waitingB.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        waitingB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(waitingB);
        waitingB.setBounds(310, 260, 180, 130);

        waitingC.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        waitingC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(waitingC);
        waitingC.setBounds(550, 260, 180, 130);

        waitingA.setColumns(20);
        waitingA.setRows(5);
        jScrollPane1.setViewportView(waitingA);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 260, 220, 130);

        TVbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TV.png"))); // NOI18N
        jPanel1.add(TVbg);
        TVbg.setBounds(0, 0, 794, 400);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TVbg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel serveA;
    public static javax.swing.JLabel serveB;
    public static javax.swing.JLabel serveC;
    public static javax.swing.JTextArea waitingA;
    public static javax.swing.JTextField waitingB;
    public static javax.swing.JTextField waitingC;
    // End of variables declaration//GEN-END:variables
}
